"""Schema for the Aiven-hosted NBA injury-report store.

A change-log, not a snapshot store. Consecutive injury reports are almost
identical -- a player listed ``Out`` stays ``Out`` for dozens of them -- so one
row per (report x player) is 15-55x larger than necessary. Measured on two
complete game-days: 2,902 snapshot rows collapse to 188 spans (24/day era) and
13,302 to 244 (96/day era). Nothing is lost; a span carries the interval over
which a status held, so any historical snapshot is a range containment.

This is not merely tidier. The snapshot form is ~5.8M rows (~690 MB with
indexes) against a 1 GB instance cap that covers WAL too. It does not fit.

Two invariants are enforced here rather than left to callers, because both are
ways the store could silently produce a look-ahead error:

* ``valid_to`` is NOT NULL and clamped at ``tipoff_utc``. No span may outlive
  its own game, so an as-of read after tip returns nothing rather than a stale
  "Doubtful" that never resolved.
* ``reason_id`` is NOT NULL. Only 61.3% of ``Out`` rows are ``Injury/Illness``;
  30.0% are ``G League`` roster mechanics (Two-Way, On Assignment). A status
  without its reason is not less informative, it is misleading.

See ``docs/injury_report_db_plan.md`` for the measurements behind both.
"""

from __future__ import annotations

import psycopg
from psycopg import sql

SCHEMA = "injury_report"

#: Ordinal on purpose: severity increases with the id, so "at least doubtful"
#: is ``status_id >= 4`` and no CASE expression is needed downstream.
#: Verified closed over 404 reports / 34,505 rows spanning 2019-12 to 2026-06,
#: cross-checked against raw PDF text (agreement within 4 rows).
STATUSES: tuple[tuple[int, str], ...] = (
    (1, "available"),
    (2, "probable"),
    (3, "questionable"),
    (4, "doubtful"),
    (5, "out"),
)

STATUS_BY_LABEL: dict[str, int] = {
    "Available": 1,
    "Probable": 2,
    "Questionable": 3,
    "Doubtful": 4,
    "Out": 5,
}

#: Eras, mirroring ``fetch_data.injury_reports.archive.urls``.
#: Reason recorded when a player drops off a filed team's list before tipoff.
#: Paired with a NULL status_id; see plan section 7.
NOT_LISTED_CATEGORY = ("not_listed", "(not listed)")

ERAS: dict[str, int] = {
    "legacy_3": 1,
    "bubble_3": 2,
    "hourly_24": 3,
    "quarter_96": 4,
}

DDL_STATEMENTS: tuple[str, ...] = (
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_status (
        status_id SMALLINT PRIMARY KEY,
        code      TEXT NOT NULL UNIQUE
    )
    """,
    # Open set, unlike ir_status. New categories genuinely appear (Health and
    # Safety Protocols in 2020, Ineligible To Play in 2022), so the loader
    # inserts unseen ones rather than rejecting them. ``code`` is case-folded
    # because the NBA prints both "Not With Team" and "Not with Team".
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_reason_category (
        category_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code        TEXT NOT NULL UNIQUE,
        label       TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_reason (
        reason_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_id SMALLINT NOT NULL REFERENCES {schema}.ir_reason_category,
        detail      TEXT NOT NULL DEFAULT '',
        UNIQUE (category_id, detail)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_team (
        team_id     SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nba_team_id BIGINT NOT NULL UNIQUE,
        tricode     TEXT NOT NULL UNIQUE,
        report_name TEXT NOT NULL UNIQUE
    )
    """,
    # Local copy of the game dimension, mirroring line_history's lh_game. ~10k
    # rows; it is what lets every read join locally instead of reaching across
    # to Supabase. tipoff_utc is also what clamps spans, so it must be here.
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_game (
        game_id     TEXT PRIMARY KEY,
        game_date   DATE        NOT NULL,
        season_year SMALLINT    NOT NULL,
        tipoff_utc  TIMESTAMPTZ NOT NULL,
        team_home   TEXT        NOT NULL,
        team_away   TEXT        NOT NULL,
        -- schedule | game_time_index | injury_report. The last is a validated
        -- fallback for the 2025-26 postseason, which the schedule feed lacks.
        tipoff_source TEXT      NOT NULL DEFAULT 'schedule'
    )
    """,
    # Coverage. Without it, "the player was not listed" and "no report exists
    # for that hour" are indistinguishable, and every gap in an as-of read is a
    # guess. The S3 key is not stored -- urls.s3_key() derives it from
    # observed_at, so storing it would duplicate ~70 bytes per row.
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_report (
        report_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        observed_at TIMESTAMPTZ NOT NULL UNIQUE,
        season_year SMALLINT NOT NULL,
        era         SMALLINT NOT NULL,
        n_rows      SMALLINT NOT NULL,
        parse_ok    BOOLEAN  NOT NULL DEFAULT TRUE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_status_span (
        game_id         TEXT        NOT NULL,
        -- BIGINT: NBA person ids already reach 1,966,938,209, within 9% of the
        -- INTEGER ceiling (2,147,483,647).
        player_id       BIGINT      NOT NULL,
        team_id         SMALLINT    NOT NULL REFERENCES {schema}.ir_team,
        season_year     SMALLINT    NOT NULL,
        valid_from      TIMESTAMPTZ NOT NULL,
        valid_to        TIMESTAMPTZ NOT NULL,
        status_id       SMALLINT    REFERENCES {schema}.ir_status,
        reason_id       INTEGER     NOT NULL REFERENCES {schema}.ir_reason,
        first_report_id INTEGER     NOT NULL REFERENCES {schema}.ir_report,
        mins_to_tip     INTEGER     NOT NULL,
        is_pregame      BOOLEAN     NOT NULL,
        -- season_year trails only because Postgres requires the partition key
        -- inside the unique constraint; game_id stays leading so "everything
        -- for game X" still uses the index prefix.
        PRIMARY KEY (game_id, player_id, valid_from, season_year),
        CONSTRAINT ir_span_ordered CHECK (valid_to > valid_from),
        -- A sixth status would be a real change in what the NBA publishes and
        -- should stop the load, not land silently as an unmapped row.
        CONSTRAINT ir_span_known_status CHECK (status_id IS NULL
                                               OR status_id BETWEEN 1 AND 5)
    ) PARTITION BY LIST (season_year)
    """,
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_filing_span (
        game_id     TEXT        NOT NULL,
        team_id     SMALLINT    NOT NULL REFERENCES {schema}.ir_team,
        season_year SMALLINT    NOT NULL,
        valid_from  TIMESTAMPTZ NOT NULL,
        valid_to    TIMESTAMPTZ NOT NULL,
        submitted   BOOLEAN     NOT NULL,
        PRIMARY KEY (game_id, team_id, valid_from, season_year),
        CONSTRAINT ir_filing_ordered CHECK (valid_to > valid_from)
    ) PARTITION BY LIST (season_year)
    """,
    # Persisted so name -> player_id resolution is reproducible and reviewable,
    # rather than a fuzzy match re-run differently on every load.
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_player_alias (
        raw_name    TEXT     NOT NULL,
        team_id     SMALLINT NOT NULL REFERENCES {schema}.ir_team,
        season_year SMALLINT NOT NULL,
        player_id   BIGINT   NOT NULL,
        method      TEXT     NOT NULL,
        PRIMARY KEY (raw_name, team_id, season_year)
    )
    """,
    # A load that silently drops players is the failure mode that matters most
    # here, so every miss is recorded and counted instead of discarded.
    """
    CREATE TABLE IF NOT EXISTS {schema}.ir_unresolved (
        raw_name        TEXT NOT NULL,
        raw_team        TEXT NOT NULL,
        season_year     SMALLINT NOT NULL,
        occurrences     INTEGER NOT NULL DEFAULT 1,
        first_report_id INTEGER,
        note            TEXT,
        PRIMARY KEY (raw_name, raw_team, season_year)
    )
    """,
)

INDEX_STATEMENTS: tuple[str, ...] = (
    # Migration for instances created before tipoff_source existed.
    "ALTER TABLE {schema}.ir_game "
    "ADD COLUMN IF NOT EXISTS tipoff_source TEXT NOT NULL DEFAULT 'schedule'",
    # Migration for instances created while player_id was INTEGER. A no-op when
    # the column is already BIGINT; on the partitioned table it propagates.
    "ALTER TABLE {schema}.ir_status_span ALTER COLUMN player_id TYPE BIGINT",
    "ALTER TABLE {schema}.ir_player_alias ALTER COLUMN player_id TYPE BIGINT",
    "CREATE INDEX IF NOT EXISTS ir_report_season_idx "
    "ON {schema}.ir_report (season_year, observed_at)",
    "CREATE INDEX IF NOT EXISTS ir_game_date_idx " "ON {schema}.ir_game (game_date)",
)


def create_schema(conn: psycopg.Connection) -> None:
    """Create the schema, dimensions and both partitioned fact tables."""
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(SCHEMA))
        )
        for statement in DDL_STATEMENTS + INDEX_STATEMENTS:
            cur.execute(sql.SQL(statement.format(schema=SCHEMA)))

        for status_id, code in STATUSES:
            cur.execute(
                sql.SQL(
                    "INSERT INTO {}.ir_status (status_id, code) VALUES (%s, %s) "
                    "ON CONFLICT (status_id) DO NOTHING"
                ).format(sql.Identifier(SCHEMA)),
                (status_id, code),
            )
    conn.commit()


def partition_name(table: str, season_year: int) -> str:
    return f"{table}_{season_year}"


def create_season_partition(conn: psycopg.Connection, season_year: int) -> None:
    """Create the season partition of both fact tables if absent."""
    # Partition bounds are DDL and cannot be parameterised, so the (integer)
    # season is embedded as a literal.
    with conn.cursor() as cur:
        for table in ("ir_status_span", "ir_filing_span"):
            cur.execute(
                sql.SQL(
                    "CREATE TABLE IF NOT EXISTS {}.{} "
                    "PARTITION OF {}.{} FOR VALUES IN ({})"
                ).format(
                    sql.Identifier(SCHEMA),
                    sql.Identifier(partition_name(table, season_year)),
                    sql.Identifier(SCHEMA),
                    sql.Identifier(table),
                    sql.Literal(int(season_year)),
                )
            )
    conn.commit()


def drop_schema(conn: psycopg.Connection) -> None:
    """Tear everything down. Used by ``--reset``."""
    # Callers may reach here from an except: block with a failed transaction.
    conn.rollback()
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(SCHEMA))
        )
    conn.commit()
