"""Tipoffs the NBA season-schedule feed has wrong.

The feed keeps the *originally scheduled* time, so any game the league moved --
a flexed TV slot, the January 2026 storm, a postponement weeks later -- keeps a
stale tipoff. Everything timed against it then misplaces the game: line-history
``mins_to_tip`` / ``is_pregame`` label live ticks pre-game when the real tip was
earlier (``0022501111`` was stored three weeks after it was played), and the
injury-report "as of tip" cut lands at the wrong moment.

The reference is the NBA daily scoreboard (``ScoreboardV3.gameTimeUTC``) of the
date the game was played. On the 66 disagreements checked on 2026-09-17 it
matched the SBR page tipoff to the minute, and the market agreed: books trade
live after it and go quiet at it.

The corrections themselves are generated into ``tipoff_corrections_data.py``
by ``scripts/line_history/reconcile_tipoffs.py --write-corrections``;
``apply_tipoff_corrections`` runs inside ``fetch_schedules``, so every consumer
of the feed gets them.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from nba_ou.fetch_data.nba_schedule.tipoff_corrections_data import CORRECTED_TIPOFFS

CORRECTIONS_DATA_PATH = Path(__file__).with_name("tipoff_corrections_data.py")


@dataclass(frozen=True)
class TipoffCorrection:
    game_id: str
    feed_tipoff_utc: pd.Timestamp
    tipoff_utc: pd.Timestamp


TIPOFF_CORRECTIONS: dict[str, TipoffCorrection] = {
    game_id: TipoffCorrection(
        game_id, pd.Timestamp(feed).tz_convert("UTC"), pd.Timestamp(played).tz_convert("UTC")
    )
    for game_id, (feed, played) in CORRECTED_TIPOFFS.items()
}


def apply_tipoff_corrections(schedule: pd.DataFrame) -> pd.DataFrame:
    """Override feed tipoffs with the corrected ones, where listed."""
    if schedule is None or schedule.empty or "tipoff_utc" not in schedule.columns:
        return schedule
    out = schedule.copy()
    ids = out["game_id"].astype(str)
    hit = ids.isin(TIPOFF_CORRECTIONS)
    if hit.any():
        tipoff = pd.to_datetime(out["tipoff_utc"], utc=True)
        tipoff[hit] = [TIPOFF_CORRECTIONS[g].tipoff_utc for g in ids[hit]]
        out["tipoff_utc"] = tipoff
        if "tipoff_et" in out.columns:
            out.loc[hit, "tipoff_et"] = [
                TIPOFF_CORRECTIONS[g]
                .tipoff_utc.tz_convert("America/New_York")
                .strftime("%Y-%m-%dT%H:%M:%S")
                for g in ids[hit]
            ]
    return out


def render_corrections_module(
    corrections: Mapping[str, tuple[pd.Timestamp, pd.Timestamp]],
) -> str:
    """Source of ``tipoff_corrections_data.py`` for ``corrections``."""
    lines = [
        '"""Generated by scripts/line_history/reconcile_tipoffs.py --write-corrections.',
        "",
        "game_id -> (tipoff in the season-schedule feed, tipoff as played per the NBA",
        "daily scoreboard), both UTC. Do not edit by hand; see tipoff_corrections.py.",
        '"""',
        "",
        "CORRECTED_TIPOFFS: dict[str, tuple[str, str]] = {",
    ]
    for game_id in sorted(corrections):
        feed, played = corrections[game_id]
        lines.append(
            f'    "{game_id}": ("{pd.Timestamp(feed).tz_convert("UTC").isoformat()}", '
            f'"{pd.Timestamp(played).tz_convert("UTC").isoformat()}"),'
        )
    lines.append("}")
    return "\n".join(lines) + "\n"
